# Generated by Django 3.2.4 on 2021-06-16 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_outstandingbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('NEW_TRANSACTION', 'NEW_TRANSACTION'), ('ACCEPTED_TRANSACTION', 'ACCEPTED_TRANSACTION'), ('DECLINED_TRANSACTION', 'DECLINED_TRANSACTION')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
