# Generated by Django 3.2.3 on 2021-06-03 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210529_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'ACCEPTED'), (3, 'DECLINED')], default=1)),
                ('declined_comment', models.TextField(null=True)),
                ('message', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
